### ISSUE TITLE
Mediapipe can't locate data files.

### ISSUE THREAD

**Issue by pedroarroyo** [rajkundu/libmp-example#6]
Hi, 

The project builds fine, however when I try to run it, it looks like libMP can't locate the tflite files.  Do they need to be copied over to the same folder as the executable?  Or is it possible to pass a path into mediapipe?

I20230825 11:23:36.616098 303962 libmp_impl.cpp:74] Status: INVALID_ARGUMENT: Graph has errors: 
Calculator::Open() for node "facelandmarkfrontcpu__facelandmarkcpu__facelandmarksmodelloader__LocalFileContentsCalculator" failed: ; Can't find file: mediapipe/modules/face_landmark/face_landmark_with_attention.tflite

**Comment by pedroarroyo** [comment]
Resolved by setting the working directory for my debug session to the mediapipe folder.

**Comment by rajkundu** [comment]
Sorry I didn't see this in time to reply - thanks for sharing your solution!
